version: '3'
services:

  web:
    build: .
    container_name: parikshana_web
    command: gunicorn -b 0.0.0.0:8000 -w 5 parikshana.wsgi:application
    ports:
      - 8000
    depends_on:
      - nginx
      - postgres
    volumes:
      - .:/code
    env_file:
      - .env

  nginx:
    container_name: nginx_compiler
    restart: unless-stopped
    build: ./server_config
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./media:/media
    environment:
      SECRET_KEY: ${secret_key}


  postgres:
    image: postgres:14.4-alpine3.16
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_DB: ${postgres_db}
      POSTGRES_PASSWORD: ${postgres_password}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.6
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_default_email}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_default_password}
    ports:
    - 80

  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    environment:
    - ALLOW_EMPTY_PASSWORD=NO
    - REDIS_PASSWORD=${redis_password}
    ports:
      - "6379:6379"
