version: '3'
services:

  web:
    image: django_web
    container_name: parikshana_web
    command: gunicorn -b 0.0.0.0:8000 -w 6 parikshana.wsgi:application --reload
    ports:
      - 8000
    depends_on:
      - nginx
      - postgres
    volumes:
      - .:/code
    env_file:
      - .env

  nginx:
    container_name: parikshana_nginx
    restart: unless-stopped
    build: ./server_config
    ports:
      - "80:80"
    environment:
      SECRET_KEY: ${secret_key}


  postgres:
    image: postgres:14.4-alpine3.16
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_DB: ${postgres_db}
      POSTGRES_PASSWORD: ${postgres_password}
    ports:
      - "5432:5432"


  storage:
    container_name: min.io
    image: minio/minio:RELEASE.2022-07-24T17-09-31Z
    environment:
      - MINIO_ROOT_USER=${minio_root_user}
      - MINIO_ROOT_PASSWORD=${minio_root_password}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    command: server --address ":9000" --console-address ":9001" /data


  celery_worker:
    image: django_web
    container_name: celery_worker
    command: python -m celery -A parikshana worker --loglevel=INFO --concurrency=4 -n smartworker@%n -E
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web

  celery_flower:  
    image: mher/flower
    container_name: flower
    command: celery flower --basic_auth=${flower_username}:${flower_password}
    environment:
      - CELERY_BROKER_URL=redis://${redis_username}:${redis_password}@${redis_host}:${redis_port}/
      - FLOWER_PORT=8888
      - TZ=Asia/Kolkata
    ports:  
      - 8888:8888
    volumes:
      - ./flower_data:/data
    depends_on:
      - celery_worker

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.6
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_default_email}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_default_password}
    ports:
    - 9999:80

  # redis:
  #   container_name: redis
  #   image: redis/redis-stack-server
  #   volumes:
  #     - ./redis:/data
  #   environment:
  #   - ALLOW_EMPTY_PASSWORD=NO
  #   - REDIS_PASSWORD=${redis_password}
  #   - REDIS_USERNAME=${redis_username}
  #   ports:
  #     - "6379:6379"
