# Generated by Django 4.0.6 on 2022-08-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
