# Generated by Django 4.0.6 on 2022-08-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_schoolsection_delete_schoolclass'),
        ('test_app', '0002_test_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_section', to='school_app.schoolsection'),
        ),
    ]
