# Generated by Django 4.0.6 on 2022-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_test_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
