# Generated by Django 4.0.6 on 2022-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_remove_question_created_by_remove_question_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
