# Generated by Django 4.0.6 on 2022-08-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_question_correct_option_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
