# Generated by Django 4.0.6 on 2022-08-21 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_remove_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), null=True, size=4),
        ),
    ]
