# Generated by Django 4.0.6 on 2022-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_shuffled',
            field=models.BooleanField(default=False),
        ),
    ]
