# Generated by Django 4.0.6 on 2022-08-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student_name',
        ),
    ]
