# Generated by Django 4.0.6 on 2022-08-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0002_remove_studentgrade_student_id_and_more'),
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.schoolstudent'),
        ),
    ]
