# Generated by Django 4.0.6 on 2022-08-15 08:05

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('test_app', '0001_initial'),
        ('grader_app', '0003_studentgrade_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='parikshana-media'), upload_to='test_images', verbose_name='test image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('job_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[], max_length=20, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_student', to='school_app.schoolstudent')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_test', to='test_app.test')),
            ],
            options={
                'db_table': 'test_answer',
            },
        ),
    ]
