# Generated by Django 4.0.6 on 2022-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0005_alter_studentgrade_ansqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
