# Generated by Django 4.0.6 on 2022-08-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0006_alter_answersheet_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestion',
            name='answer_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_sheet', to='grader_app.answersheet'),
        ),
        migrations.AlterField(
            model_name='answeredquestion',
            name='answer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
