# Generated by Django 4.0.6 on 2022-08-07 06:34

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='parikshana-media'), upload_to='student_images', verbose_name='Object Upload'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'superadmin'), (2, 'teacher'), (3, 'admin')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'is_superadmin'), ('TEACHER', 'is_teacher'), ('ADMIN', 'is_admin')], max_length=50, null=True),
        ),
    ]
