# Generated by Django 4.0.6 on 2022-08-15 08:05

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image_alter_role_id_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='parikshana-media'), upload_to='student_images', verbose_name='User Image'),
        ),
    ]
