name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy DRF app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.parikshana_backend }}
          username: root
          password: ${{ secrets.parikshana_backend_password}}
          script: |
            cd parikshana-backend
            git pull
            docker-compose down
            docker-compose up -d
            echo "Successfully deployed"
