# Generated by Django 4.0.6 on 2022-08-15 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(related_name='school_class_students', to='school_app.schoolstudent'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(related_name='school_class_teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
