# Generated by Django 4.0.6 on 2022-08-20 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_test_pending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_app', '0002_alter_schoolclass_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_class_standard', to='test_app.standard')),
                ('students', models.ManyToManyField(related_name='school_class_students', to='school_app.schoolstudent')),
                ('teachers', models.ManyToManyField(related_name='school_class_teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school_section',
            },
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
