# Generated by Django 4.0.6 on 2022-08-25 19:29

from django.db import migrations, models
import school_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_schoolsection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudent',
            name='std_id',
            field=models.CharField(blank=True, default=school_app.models.random_gen, max_length=4, null=True, unique=True),
        ),
    ]
